# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f723f5419708630529126e96f12ce38586095979fda68c787a1d410617906f80da98b49a088f22cd10a942a5dc86e0f3c777a916dd8670618dbacd66fe38b838

test:
  secret_key_base: 91f3466a7fd162bc3e7a5f4f93021c711afefde19474508c2ce1463925ce04488707771e451c3d231a367a62e4c15e39e0a897f76e37638b21ae3976113aeede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
